<a href="https://colab.research.google.com/github/poudelef/Tensorflow-basics/blob/main/Tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.18.0'

### Creating Tensor flow with constant

In [3]:
scalar = tf.constant(1)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [4]:
# Check the number of dimensions of a tensor. ndim means number of dimensions
scalar.ndim

0

In [5]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
vector = tf.constant([[10,20,34],[30,40,23],[50,60,32]])
vector

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 20, 34],
       [30, 40, 23],
       [50, 60, 32]], dtype=int32)>

In [8]:
vector.ndim

2

In [9]:
matrix = tf.constant([[12.5,45.0],[45.3,80.9]], dtype = tf.float16)
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[12.5, 45. ],
       [45.3, 80.9]], dtype=float16)>

In [10]:
matrix.ndim

2

In [11]:
tensor = tf.constant([[[3,4],[43,34],[43,34]]])

In [12]:
tensor

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[ 3,  4],
        [43, 34],
        [43, 34]]], dtype=int32)>

In [13]:
tensor.shape

TensorShape([1, 3, 2])

In [14]:
tensor.ndim

3

In [15]:
# Scalaar : a single number
# Vector : a number with direction
# Matrix : 2- dimentional array of number
# tensor : n- dimention array of number. 1-dimentions tensor is vector and o-dimention tensor is scalar. B

### Creating Tensor with tf. variable

In [16]:
tensor = tf.Variable([10,23])

In [17]:
random_number1 = tf.random.Generator.from_seed(42)
random_number2 =  tf.random.Generator.from_seed(42)
print(random_number1.normal(shape=(1,2)))
print(random_number2)
random_number1 = random_number1.normal(shape =(3,2))
random_number2 = random_number2.normal(shape=(3,2))

random_number1, random_number2, random_number1 == random_number2

tf.Tensor([[-0.7565803  -0.06854702]], shape=(1, 2), dtype=float32)


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.9029392 , -0.12441138],
        [ 1.8243233 , -0.56251436],
        [-1.7110394 ,  1.1681837 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [18]:
non_sufle = tf.constant([[10,4],[4,3],[6,7]])
non_sufle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  4],
       [ 4,  3],
       [ 6,  7]], dtype=int32)>

### If we want our suffled tensors to be in the same order. WE need to use gloabl level random seed else we can use operation level seed to generate random tensors each time

In [19]:
# tf.random.set_seed(42) # Global level random seed
tf.random.shuffle(non_sufle,seed= 42) #operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  7],
       [ 4,  3],
       [10,  4]], dtype=int32)>

In [20]:
tf.ones([10,7])


<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [21]:
tf.ones(shape=(10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
tf.zeros([5,2],dtype=tf.dtypes.int16)

<tf.Tensor: shape=(5, 2), dtype=int16, numpy=
array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int16)>

### Turn NumPy arrays intn tensors


 The main difference between numpy array and tensors are tensors can be run on a GPU (much faster for numerical computing)

In [23]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [24]:
A = tf.constant(numpy_A, shape=(2,2,3,2))
A

<tf.Tensor: shape=(2, 2, 3, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]],


       [[[13, 14],
         [15, 16],
         [17, 18]],

        [[19, 20],
         [21, 22],
         [23, 24]]]], dtype=int32)>

In [25]:
2*2*3*2


24

### Getting information from tensors

* shape
* Rank - ndim
* Axis or dimensions
* size - total item in tensor

In [26]:
A = tf.constant([[[[3,4]]]])
A.ndim

4

In [27]:
rank_4_tf = tf.zeros([2,3,4,5])

In [28]:
rank_4_tf

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
rank_4_tf[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [30]:
rank_4_tf[0][0]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [31]:
rank_4_tf.shape, rank_4_tf.ndim, tf.size(rank_4_tf)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [32]:
# Attritutes of tensors
print("Data type of every element: ", rank_4_tf.dtype)
print("Number of dimensions (rank): ", rank_4_tf.ndim)
print("Shape of tensor: ", rank_4_tf.shape)
print("Elements along the 0 axis: ", rank_4_tf.shape[0])
print("Elements along the last axis: ", rank_4_tf.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tf))
print("Total number of elements in our tensor: ", tf.size(rank_4_tf).numpy())

Data type of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor:  120


### Indexing tensors

Tensors can be indexed ust like python


In [33]:
# get the first 2 element of dimentions

In [34]:
rank_4_tf

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [35]:
rank_4_tf[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [36]:
# Get the first element from each dimention from each index except for the finle one
print(rank_4_tf[0,0,0])
print('------------------') # below one is correct
print(rank_4_tf[:1,:1,:1])

tf.Tensor([0. 0. 0. 0. 0.], shape=(5,), dtype=float32)
------------------
tf.Tensor([[[[0. 0. 0. 0. 0.]]]], shape=(1, 1, 1, 5), dtype=float32)


In [37]:
# Get the first element from each dimention from each index except for the second last one
print(rank_4_tf[:1,:1,:,:1])

tf.Tensor(
[[[[0.]
   [0.]
   [0.]
   [0.]]]], shape=(1, 1, 4, 1), dtype=float32)


In [38]:
rank_4_tf.shape

TensorShape([2, 3, 4, 5])

In [39]:
2*3*4*5

120

In [40]:
8*15

120

### Manipulating tensors

**Basic Opearation**
+ , -, / , *

In [41]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 12],
       [ 8,  9]], dtype=int32)>

In [42]:
# original value doesn't change unless we do  =
tensor
# we can do al operation -, /, *

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [43]:
# we can use tensor flow libray
tf.math.multiply(tensor,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 35],
       [15, 20]], dtype=int32)>

### Matrix multiplication

In [44]:
# Matrix multipliction in tensorfow
a = tf.constant([1,2,5,7,2,1,3,3,3], shape=(3,3))
print(a)
b = tf.constant([3,5,6,7,1,8], shape=(3,2))
print(b)
tensor = tf.linalg.matmul(a,b)
tensor

tf.Tensor(
[[1 2 5]
 [7 2 1]
 [3 3 3]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [45]:
# Matrix multiplication in python
a @ b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

##### Mulplying two tensores of same shape

In [46]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

In [47]:
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

In [48]:
# X @ Y # error occurs

In [49]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [50]:
Y = tf.reshape(Y, shape =(2,3))
print(Y)

tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


In [51]:
X @ Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [52]:
Y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [53]:
New_datatype = tf.cast(Y, dtype = tf.float16)
New_datatype

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float16)>

### Aggregating Tensors

Aggregating tensoes means reducing tensors to smaller values

In [54]:
# Getting the absolute values
D = tf.constant([-7,-10])
D, tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

Let's go through the following aggregatin
*minimum
*maximum
*mean
*sum

In [55]:
# Create a random tensor with the values between 0 to 100 of size 50
E = tf.constant(np.random.randint(0,100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([74, 18, 66, 22, 43, 22, 54, 60, 32, 94, 61, 64, 53, 81, 23,  9, 54,
       98, 13, 49, 70,  8, 28, 61, 34, 67,  5, 10, 25, 80, 57,  5,  4, 43,
       66, 21, 14, 29, 90, 97, 48,  4, 44, 81, 10, 63, 74, 73, 83, 30])>

In [56]:
E.shape, tf.size(E), E.dtype, E.ndim

(TensorShape([50]), <tf.Tensor: shape=(), dtype=int32, numpy=50>, tf.int64, 1)

In [57]:
tf.math.reduce_min(E, axis=0)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [58]:
tf.math.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [59]:
tf.math.reduce_mean(E).numpy()

46

In [60]:
# standared devation return float # see tf.std documentation
tf.math.reduce_std(tf.cast(E,dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=28.06067711228651>

In [61]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=787.4016>

### Find the postitional maximum and minimum
Create a new tensoe for finding positional mininum and maximum

In [62]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [63]:
tf.math.argmax(F) # returns index of largest value in tensor

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [64]:
F[42]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [65]:
tf.math.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [66]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [67]:
F[(tf.argmin(F))]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

### Squeezing tensors(removing all single dimennsions)

In [68]:
tf.random.set_seed(42)
G = tf.random.uniform(shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [69]:
G_sqeezed = tf.squeeze(G)
G_sqeezed, G_sqeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensors

In [70]:
some_list = [1,2,4,2,3]
tf.one_hot(some_list, depth=2)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

### Tensor and Numpy
Tensoe flow interacts nicely with Numpy array

In [72]:
J = tf.constant(np.array([3,5,3]))
J

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([3, 5, 3])>

In [73]:
np.array(J)

array([3, 5, 3])

In [74]:
J.numpy()

array([3, 5, 3])

### Finding access to GPUs
Go to runtime and select for chagge run time and you can select GPU or TPU from there

In [1]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
# This shows what kind of GPU you are using and google colab doesn't let us select GPU of our choice
!nvidia-smi

Fri Feb  7 01:01:29 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

### Exercise till
* Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

* Find the shape, rank and size of the tensors you created in 1.

* Create two tensors containing random values between 0 and 1 with shape [5, 300].

* Multiply the two tensors you created in 3 using matrix multiplication.

* Multiply the two tensors you created in 3 using dot product.

* Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

* Find the min and max values of the tensor you created in 6 along the first axis.

* Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

* Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

* One-hot encode the tensor you created in 9.

In [4]:
import tensorflow as tf

In [5]:
V = tf.constant([2,4,6,3])
V

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 3], dtype=int32)>

In [6]:
S = tf.constant(1)
S

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
M = tf.constant([[2,3,5,6],[6,3,7,8]])
M

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[2, 3, 5, 6],
       [6, 3, 7, 8]], dtype=int32)>

In [8]:
V.shape, tf.size(V), V.ndim
S.shape, tf.size(S), S.ndim
M.shape, tf.size(M), M.ndim

(TensorShape([2, 4]), <tf.Tensor: shape=(), dtype=int32, numpy=8>, 2)

In [23]:
A = tf.random.Generator.from_seed(42)
A = A.normal(shape=(5,300))
A

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, ..., -1.0718341 ,
        -1.0722276 , -0.00586287],
       [-0.8805103 , -0.32426047, -2.4847078 , ...,  0.16512105,
         1.155565  , -0.10707551],
       [-1.5306779 , -0.8620293 , -0.16359143, ...,  0.34288087,
         1.216793  , -1.2429299 ],
       [ 0.8432426 , -0.23379941,  0.42763978, ..., -1.0428714 ,
        -0.73970354,  0.0177109 ],
       [ 0.04888754, -0.66408694, -1.787366  , ...,  0.1947453 ,
         0.5656089 ,  0.18439198]], dtype=float32)>

In [24]:
B = tf.random.Generator.from_seed(22)
B = B.normal(shape=(5,300))
B

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[-0.7531523 ,  2.0261486 , -0.06997604, ...,  1.1928992 ,
         1.7263643 ,  0.71513796],
       [-1.0779938 , -1.1893024 ,  0.08200742, ...,  1.2378134 ,
        -0.5333003 ,  0.5499724 ],
       [ 0.8250944 ,  0.02531349,  1.0933132 , ..., -0.9221158 ,
         1.3876396 ,  0.23198044],
       [-0.48676503, -1.3900983 ,  0.30898732, ..., -1.1654662 ,
        -1.4466094 ,  0.16346607],
       [ 0.53709805,  1.4272277 , -0.9052965 , ..., -0.36931053,
        -0.01361591,  0.8295046 ]], dtype=float32)>

In [32]:
print('size of A: ',tf.size(A).numpy())
print('shape of A: ',A.shape)
print('size of B: ',tf.size(B).numpy())
print('shape of B: ',B.shape)

size of A:  1500
shape of A:  (5, 300)
size of B:  1500
shape of B:  (5, 300)


In [33]:
B = tf.reshape(B, shape=(300,5))

In [34]:
B.shape

TensorShape([300, 5])

In [36]:
Mul_AB = tf.linalg.matmul(A,B)

In [39]:
C = tf.random.Generator.from_seed(100)
C= C.normal(shape=(244,244,3))

In [42]:

D = tf.math.reduce_max(C, axis=0).numpy()
D

array([[3.103144 , 2.423616 , 2.0176623],
       [2.4235914, 2.631507 , 2.8808382],
       [2.9852548, 2.4131224, 2.5550091],
       [3.1077476, 2.7493734, 2.9750853],
       [3.335201 , 2.6520627, 2.7225552],
       [2.458612 , 4.143849 , 3.2683666],
       [3.6747038, 3.2083302, 2.6869996],
       [2.7170846, 2.2460382, 2.5325427],
       [2.9892633, 2.3748603, 1.814754 ],
       [2.412548 , 2.9597194, 2.693442 ],
       [2.8594859, 3.2264588, 2.2900276],
       [2.1735067, 2.5657833, 3.2124982],
       [2.1314619, 2.922551 , 2.3711767],
       [2.8399048, 3.2045388, 2.8657808],
       [2.5648057, 2.8447542, 2.7760174],
       [2.4880695, 2.7583709, 3.7233512],
       [2.7557178, 2.8227265, 3.2576523],
       [2.2525334, 3.1800234, 3.019183 ],
       [3.5695724, 2.463126 , 2.599501 ],
       [2.9465792, 3.120509 , 3.1958346],
       [2.3338425, 2.8823073, 2.9649973],
       [2.765907 , 2.9976327, 3.0486042],
       [2.8180327, 2.5438585, 2.59572  ],
       [3.1579332, 2.742517 , 2.23

In [44]:
tf.math.argmax(tf.constant([1,4,3,4,2,5,7,6,4,5]))

<tf.Tensor: shape=(), dtype=int64, numpy=6>